### PR TITLE
Fix overlapping icons

### LINKED ISSUE #223: Overlapping Icons
**General Info (please complete the following information):**
 - Modpack version: 3.7.0
 - Client or server: Client
 - Packmode: both
 - Own modifications to the modpack: -

**Describe the bug**
The icons of the RFTools environmental controller and the infobox from The One Probe are overlapping.

**To Reproduce**
E.g.:
1. setup RFTools environmental controller
2. power it up
3. look top left corner

**Screenshots**
Bugimg

### PR DESCRIPTION
**Pull request by FaiThiX**
Fixed #223

### CODE REVIEW

**Comment by FaiThiX** [comment]
What the "fix" looks like
NewImg

**Comment by Irgendwer01** [comment]
@FaiThiX wouldn't it be maybe better to move it to the right instead of moving it down? :thinking:

**Comment by FaiThiX** [comment]
@Irgendwer01 I dont think so, because there is the Journeymap located.

**Comment by Irgendwer01** [comment]
oh ye, complete forgot about that

**Comment by Erani0** [comment]
With /topcfg you can move it ingame 
With no config edit

**Comment by FaiThiX** [comment]
@Erani0 but who really knows about that command? I think its better to fix it inside the config rather than the user must search for this command.

**Comment by Erani0** [comment]
Is this config edit gui scalable?
Not all play on big screens or smalltalk gui

**Comment by Erani0** [comment]
Addendum after moving the gui 1 time and moving it back to its original position at the top left, the change is immediately obsolete and so the player has to change it manually in the config

**Pull request merged**
